### ISSUE TITLE
not enough information to fix: "<no output available>"

### ISSUE THREAD

**Issue by schettino72** [pytest-dev/plugincompat#14]
for pytest-incremental 0.4.2 on py27 The result is "?" and the output is: `<no output available>`

Any idea how can I fix that? is it my plugin problem?

**Comment by nicoddemus** [comment]
Hi @schettino72,

Sometimes the travis job for plugincompat [fails with a xmlrpclib error](https://travis-ci.org/pytest-dev/plugincompat/builds/61558434), then information about new packages like pytest-incremental 0.4.2 won't be pushed to the site... since it happens only occasionally, I never bothered to look into it.

That job runs daily so usually the next job succeeds so this is not a big deal. In any case, I just ran it manually it succeeded, and information about pytest-incremental is up on the site. :smile:

Cheers, :beers:
